DROP TABLE AUTH_SERVICE.USERS CASCADE;

CREATE TABLE AUTH_SERVICE.USERS(
	ID UUID DEFAULT gen_random_uuid() PRIMARY KEY,
	EMAIL VARCHAR(255) UNIQUE NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	ROLE VARCHAR(50) DEFAULT 'USER',
	IS_VERIFIED BOOLEAN DEFAULT FALSE,
	UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, -- Automatically sets the update timestamp
	CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP -- Automatically sets the creation timestamp
);